### ISSUE TITLE
PHP Warning: Array to string conversion in pgp.php:873

### ISSUE THREAD

**Issue by ceskyDJ** [the-djmaze/snappymail#1719]
**Describe the bug**

Hi there! I found this PHP warning message in my Docker Compose logs:
```
snappymail-1  | [2024-08-26 11:14:07.132][51c55be3] PHP[WARNING]: Array to string conversion /snappymail/snappymail/v/2.37.2/app/libraries/snappymail/gpg/pgp.php [line:873, code:2]
snappymail-1  | NOTICE: PHP message: PHP Warning:  Array to string conversion in /snappymail/snappymail/v/2.37.2/app/libraries/snappymail/gpg/pgp.php on line 873
snappymail-1  | gpgconf: Note: '--homedir' is not considered an option
```

**To Reproduce**
1. Use this `docker-compose.yml`:
```yaml
version: '2'
services:
  snappymail:
    image: djmaze/snappymail:latest
    ports:
      - 8888:8888
    environment:
      - TZ=${TZ}
      - DEBUG=false
    volumes:
      - snappymail:/var/lib/snappymail
    networks:
      - default
      - db-network
      - redis-network
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true

  mysql:
    image: mariadb:10
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQLROOT}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASS}
      - MYSQL_DATABASE=${MYSQLNAME}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db-network
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true

  redis:
    image: redis:7-alpine
    environment:
      - TZ=${TZ}
    networks:
      - redis-network
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  default:
  db-network:
    internal: true
  redis-network:
    internal: true

volumes:
  mysql:
    driver: local
  snappymail:
    driver: local
```
2. Run containers: `docker compose up -d`
3. See this error in logs after some actions in Snappymail's web interface (I think it occurs when I'm sending and e-mail) — `docker compose logs`:
```
snappymail-1  | [2024-08-26 11:14:07.132][51c55be3] PHP[WARNING]: Array to string conversion /snappymail/snappymail/v/2.37.2/app/libraries/snappymail/gpg/pgp.php [line:873, code:2]
snappymail-1  | NOTICE: PHP message: PHP Warning:  Array to string conversion in /snappymail/snappymail/v/2.37.2/app/libraries/snappymail/gpg/pgp.php on line 873
snappymail-1  | gpgconf: Note: '--homedir' is not considered an option
```

**Expected behavior**
No PHP warning and no gpgconf note appear in Docker compose logs.

**Please complete the following information:**
- Browser: Brave 1.68.134, Chromium: 127.0.6533.88 (Official Build) (64-bit)
- IMAP daemon: dovecot (Mailcow)
- PHP version: 8.2.22
- SnappyMail Version: 2.37.2
- Mode: Docker Compose

**Debug/logging information**
[Read here how to log](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)
- [ ] I've placed them here (few lines) or as attachments (many lines)
