### ISSUE TITLE
[branding] in application.ini

### ISSUE THREAD

**Issue by lota** [the-djmaze/snappymail#238]
In rainloop licensed version, was possible set some values
from admin URL /?admin#/branding
in particular "login logo", inside old application.ini on Rainloop installation I have

```
[branding]
login_logo = "my_background_coustom_logo.jpg"
login_background = "my_background_coustom_background.jpg"
login_desc = "My Webmail"
login_css = ""
user_css = ""
user_logo = "my_background_coustom_logo1.jpg"
user_logo_title = "Custom name"
user_logo_message = "my_background_coustom_background1.jpg"
user_iframe_message = ""
welcome_page_url = ""
welcome_page_display = "none"
```

are possible add at least *login_logo*?

TIA
Alessandro

**Comment by the-djmaze** [comment]
`Custom Branding options` (like the logo) are a RainLoop "Premium" feature.
That's why they are not in SnappyMail.

There are many ways to add your own branding anyway.

The best way is a [custom theme](https://github.com/the-djmaze/snappymail/wiki/Custom-Themes) as it allows you to do a lot of things.
And then:
```css
#V-Login .descWrapper {
	background: url('/path/to/custom/logo.png');
	overflow: hidden;
	text-indent: -100em;
}
```
