### ISSUE TITLE
Failed on Integrity check

### ISSUE THREAD

**Issue by elhananjair** [the-djmaze/snappymail#790]
**Describe the bug**
I saw an error on Nextcloud administration setting about integrity check and I just checked out snappymail and that is the problem which is making this error. 

**To Reproduce**
1. Go to terminal
2. write this command inside NC_DIR, `sudo -u apache php occ integrity:check-app snappymail`
3. Check the output of the command, which shows this message: "Signature data not found."

**Expected behavior**
Snappymail should be signed

**Screenshots**
![image](https://user-images.githubusercontent.com/69236638/209322614-157eb480-bcd6-4137-814b-2255f04f6069.png)

**Please complete the following information:**
- Browser: Firefox 108
- IMAP daemon: [e.g. courier, dovecot]
- PHP version: 8.0.6
- SnappyMail Version: 2.24.0

**[Debug/logging information](https://github.com/the-djmaze/snappymail/wiki/FAQ#how-do-i-enable-logging)**
Place them here (few lines) or as attachments (many lines)

**Additional context**

**Comment by the-djmaze** [comment]
Correct, we don't ship a signature.json file in NextCloud

**Comment by elhananjair** [comment]
@the-djmaze I saw this issue mentioned on the new release, though the issue is still there.

**Comment by the-djmaze** [comment]
The issue is now a different error.
I've figured out that Nextcloud uses PSS padded signatures and OpenSSL in PHP does not support PSS padding (bug report is open at PHP).

So i need to install phpseclib and generate signature with that library.

**Comment by the-djmaze** [comment]
```
php occ integrity:check-app snappymail
  - FILE_MISSING:
    - app/.htaccess:
      - expected: 953c8493084566272a9960a1cfb8b812570278e39eb1aa1d6e855a46d3c240b08a7b9cbd2569ce2332373fc6c80e22c8b2434ff5b02e4a936c056cdc88a4130b
      - current: 
    - app/snappymail/v/2.24.2/app/.htaccess:
      - expected: e371717e9e269ef76652e47d2e911d2e082d1fb1fe9cbdba9befb68a63a3d3942646998479a3a51a18fe835a9f24ce240882b3b729a2a01147414e41cc676cf8
      - current: 
    - app/snappymail/v/2.24.2/static/.htaccess:
      - expected: bc67e2c228fd8cf72ec9bdf035bec6ae9d5833146e3e37cd43fa89e331d4c169f4e1c63d439c172acb9f1ab646f233f96ca7766b5c3a02f985fba1dfdf079bd3
      - current: 
```

There seems to be a bug in Nextcloud that it does not extract the `.htaccess` files from the package.
Have to find out why that is.
