### ISSUE TITLE
Menu is under the message content zone

### ISSUE THREAD

**Issue by Massedil** [the-djmaze/snappymail#928]
**Describe the bug**

**To Reproduce**
1. Select one or more emails
2. Click on the menu button

**Expected behavior**
The menu is on top of the message content zone.

**Screenshots**
![1](https://user-images.githubusercontent.com/20357783/217496757-6f194d1f-16e5-42ad-9cb8-9eeda69a808d.png)

**Please complete the following information:**
- Browser: Firefox 109
- SnappyMail Version: 2.25.4

**Comment by the-djmaze** [comment]
Currently i made a workaround but that disables the native resize corner.

The only way to get that back is using
```css
#rl-right {
	display: flex;
}
#V-MailMessageView {
	overflow: auto;
	position: relative;
	width: 100%;
}
```
But that also has some issues to solve.
